=== lmstudio-ai/model-catalog/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "_descriptorVersion": {
        "type": "string",
        "enum": ["0.0.1"]
      },
      "datePublished": {
        "type": "string",
        "format": "date-time"
      },
      "name": {
        "type": "string"
      },
      "resources": {
        "type": "object",
        "properties": {
          "canonicalUrl": {
            "type": "string",
            "format": "uri"
          },
          "paperUrl": {
            "type": "string",
            "format": "uri"
          },
          "downloadUrl": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": ["canonicalUrl", "downloadUrl"]
      },
      "author": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "blurb": {
            "type": "string"
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": ["name", "blurb", "url"]
      },
      "numParameters": {
        "type": "string",
        "enum": ["3B", "7B", "13B", "15B", "30B", "40B", "65B", "unknown"]
      },
      "trainedFor": {
        "type": "string",
        "enum": ["chat", "instruct", "code_completion", "other"]
      },
      "arch": {
        "type": "string",
        "enum": ["llama", "pythia", "gpt-neo-x", "gpt-j", "mpt", "replit", "starcoder", "falcon", "mistral"]
      },
      "description": {
        "type": "string"
      },
      "files": {
        "type": "object",
        "properties": {
          "highlighted": {
            "type": "object",
            "properties": {
              "economical": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  }
                },
                "required": ["name"]
              },
              "most_capable": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  }
                },
                "required": ["name"]
              }
            }
          },
          "all": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/ModelFile"
            }
          }
        },
        "required": ["highlighted", "all"]
      }
    },
    "required": ["_descriptorVersion", "datePublished", "name", "resources", "author", "numParameters", "trainedFor", "arch", "files"]
  },
  "definitions": {
    "ModelFile": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string",
          "format": "uri"
        },
        "sizeBytes": {
          "type": "number"
        },
        "quantization": {
          "type": "string",
          "enum": ["q4_0", "q4_1", "q5_0", "q5_1", "q8_0", "Q2_K", "Q3_K_S", "Q3_K_M", "Q3_K_L", "Q4_K_S", "Q4_K_M", "Q5_K_S", "Q5_K_M", "Q6_K", "unknown"]
        },
        "format": {
          "type": "string"
        },
        "sha256checksum": {
          "type": "string"
        },
        "publisher": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "socialUrl": {
              "type": "string",
              "format": "uri"
            }
          },
          "required": ["name", "socialUrl"]
        },
        "respository": {
          "type": "string"
        },
        "repositoryUrl": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": ["name", "url", "sizeBytes", "quantization", "format", "sha256checksum", "publisher", "respository", "repositoryUrl"]
    }
  }
}

=== lmstudio-ai/model-catalog/models/OpenHermes-2.5-Mistral-7B.json
{
  "_descriptorVersion": "0.0.1",  
  "datePublished": "2023-10-29T21:27:30",
  "name": "OpenHermes 2.5 Mistral 7B",
  "description": "OpenHermes 2.5 Mistral 7B is an advanced iteration of the OpenHermes 2 language model, enhanced by training on a significant proportion of code datasets. This additional training improved performance across several benchmarks, notably TruthfulQA, AGIEval, and the GPT4All suite, while slightly decreasing the BigBench score. Notably, the model's ability to handle code-related tasks, measured by the humaneval score, increased from 43% to 50.7%. The training data consisted of one million entries, primarily sourced from GPT-4 outputs and other high-quality open datasets. This data was rigorously filtered and standardized to the ShareGPT format and subsequently processed using ChatML by the axolotl tool.",
  "author": {
    "name": "Teknium",
    "url": "https://huggingface.co/teknium",
    "blurb": ""
  },
  "numParameters": "7B",
  "resources": {
    "canonicalUrl": "https://huggingface.co/teknium/OpenHermes-2.5-Mistral-7B",
    "downloadUrl": "https://huggingface.co/TheBloke/OpenHermes-2.5-Mistral-7B-GGUF"
  },
  "trainedFor": "chat",
  "arch": "mistral",
  "files": {
    "highlighted": {
      "economical": {
        "name": "openhermes-2.5-mistral-7b.Q4_K_S.gguf"
      },
      "most_capable": {
        "name": "openhermes-2.5-mistral-7b.Q6_K.gguf"
      }
    },
    "all": [
      {
        "name": "openhermes-2.5-mistral-7b.Q4_K_S.gguf",
        "url": "https://huggingface.co/TheBloke/OpenHermes-2.5-Mistral-7B-GGUF/resolve/main/openhermes-2.5-mistral-7b.Q4_K_S.gguf",
        "sizeBytes": 4140385024,
        "quantization": "Q4_K_S",
        "format": "gguf",
        "sha256checksum": "5ae9c3c11ce520a2360dcfca1f4e38392dc0b7a49413ce6695857a5148a71d35",
        "publisher": {
          "name": "TheBloke",
          "socialUrl": "https://twitter.com/TheBlokeAI"
        },
        "respository": "TheBloke/OpenHermes-2.5-Mistral-7B-GGUF",
        "repositoryUrl": "https://huggingface.co/TheBloke/OpenHermes-2.5-Mistral-7B-GGUF"
      },
      {
        "name": "openhermes-2.5-mistral-7b.Q6_K.gguf",
        "url": "https://huggingface.co/TheBloke/OpenHermes-2.5-Mistral-7B-GGUF/resolve/main/openhermes-2.5-mistral-7b.Q6_K.gguf",
        "sizeBytes": 5942078272,
        "quantization": "Q6_K",
        "format": "gguf",
        "sha256checksum": "cd4caa42229e973636e9d4c8db50a89593353c521e0342ca615756ded2b977a2",
        "publisher": {
          "name": "TheBloke",
          "socialUrl": "https://twitter.com/TheBlokeAI"
        },
        "respository": "TheBloke/OpenHermes-2.5-Mistral-7B-GGUF",
        "repositoryUrl": "https://huggingface.co/TheBloke/OpenHermes-2.5-Mistral-7B-GGUF"
      }
    ]
  }
}

=== lmstudio-ai/model-catalog/models/Mistral-7B-Instruct-v0.1.json
{
  "_descriptorVersion": "0.0.1",  
  "datePublished": "2023-09-27T16:12:57",
  "name": "Mistral 7B Instruct v0.1",
  "description": "The Mistral-7B-Instruct-v0.1 is a Large Language Model (LLM) developed by Mistral AI. This LLM is an instruct fine-tuned version of a generative text model, leveraging a variety of publicly available conversation datasets. The model's architecture is based on a transformer model, featuring Grouped-Query Attention, Sliding-Window Attention, and a Byte-fallback BPE tokenizer. To utilize the instruction fine-tuning capabilities, prompts should be enclosed within [INST] and [/INST] tokens. The initial instruction should commence with a beginning-of-sentence id, whereas subsequent instructions should not. The generation process by the assistant will terminate with the end-of-sentence token id. For detailed information about this model, refer to the release blog posts by Mistral AI.",
  "author": {
    "name": "Mistral AI",
    "url": "https://mistral.ai/",
    "blurb": "Mistral AI's mission is to spearhead the revolution of open models."
  },
  "numParameters": "7B",
  "resources": {
    "canonicalUrl": "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1",
    "paperUrl": "https://mistral.ai/news/announcing-mistral-7b/",
    "downloadUrl": "https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF"
  },
  "trainedFor": "chat",
  "arch": "mistral",
  "files": {
    "highlighted": {
      "economical": {
        "name": "mistral-7b-instruct-v0.1.Q4_K_S.gguf"
      },
      "most_capable": {
        "name": "mistral-7b-instruct-v0.1.Q6_K.gguf"
      }
    },
    "all": [
      {
        "name": "mistral-7b-instruct-v0.1.Q4_K_S.gguf",
        "url": "https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q4_K_S.gguf",
        "sizeBytes": 4140373664,
        "quantization": "Q4_K_S",
        "format": "gguf",
        "sha256checksum": "f1b7f1885029080be49aff49c83f87333449ef727089546e0d887e2f17f0d02e",
        "publisher": {
          "name": "TheBloke",
          "socialUrl": "https://twitter.com/TheBlokeAI"
        },
        "respository": "TheBloke/Mistral-7B-Instruct-v0.1-GGUF",
        "repositoryUrl": "https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF"
      },
      {
        "name": "mistral-7b-instruct-v0.1.Q6_K.gguf",
        "url": "https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q6_K.gguf",
        "sizeBytes": 5942064800,
        "quantization": "Q6_K",
        "format": "gguf",
        "sha256checksum": "dfb053cb8d5f56abde8f56899ffe0d23e1285a423df0b65ea3f3adbb263b22c2",
        "publisher": {
          "name": "TheBloke",
          "socialUrl": "https://twitter.com/TheBlokeAI"
        },
        "respository": "TheBloke/Mistral-7B-Instruct-v0.1-GGUF",
        "repositoryUrl": "https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF"
      },
      {
        "name": "ggml-model-q4_0.gguf",
        "url": "https://huggingface.co/baghelz/OpenHermes-2.5-neural-chat-v3-3-Slerp/resolve/main/ggml-model-q4_0.gguf",
        "sizeBytes": 4108916352,
        "quantization": "q4_0",
        "format": "gguf",
        "sha256checksum": "0d82f9d0e9d1757c81ffe6cc5f7cf47a772e87d0e7e24c8e742417e7e97646af",
        "publisher": {
          "name": "baghelz",
          "socialUrl": "https://twitter.com/ManishBaghelz"
        },
        "respository": "baghelz/OpenHermes-2.5-neural-chat-v3-3-Slerp",
        "repositoryUrl": "https://huggingface.co/baghelz/OpenHermes-2.5-neural-chat-v3-3-Slerp"
      },
      {
        "name": "ggml-model-q8_0-v2.gguf",
        "url": "https://huggingface.co/baghelz/OpenHermes-2.5-neural-chat-v3-3-Slerp/resolve/main/ggml-model-q8_0-v2.gguf",
        "sizeBytes": 7695857280,
        "quantization": "q8_0",
        "format": "gguf",
        "sha256checksum": "aeff45c3bb4cbac4dd2adf19e1564235152e952725d9f15f527b333b40944d2e",
        "publisher": {
          "name": "baghelz",
          "socialUrl": "https://twitter.com/ManishBaghelz"
        },
        "respository": "baghelz/OpenHermes-2.5-neural-chat-v3-3-Slerp",
        "repositoryUrl": "https://huggingface.co/baghelz/OpenHermes-2.5-neural-chat-v3-3-Slerp"
     }
    ]
  }
}

=== lmstudio-ai/model-catalog/models/falcon-7b-instruct.json
{
  "_descriptorVersion": "0.0.1",  
  "datePublished": "2023-10-31T16:01:50",
  "name": "falcon-7b-instruct",
  "description": "Falcon-7B-Instruct, based on Falcon-7B, has been fine-tuned on chat and instruct datasets. It offers outstanding performance and is an excellent choice for chat and instruct applications. Falcon-7B-Instruct is part of the Falcon family of language models, known for their exceptional capabilities and openness.",
  "author": {
    "name": "Maddes8cht",
    "url": "https://huggingface.co/maddes8cht",
    "blurb": "Maddes8cht Passionate about Open Source and AI. On Hugging Face he is advocating for real open source AI models with OSI compliant licenses"
  },
  "numParameters": "7B",
  "resources": {
    "canonicalUrl": "https://huggingface.co/tiiuae/falcon-7b-instruct",
    "downloadUrl": "https://huggingface.co/maddes8cht/tiiuae-falcon-7b-instruct-gguf"
  },
  "trainedFor": "chat",
  "arch": "falcon",
  "files": {
    "highlighted": {
      "economical": {
        "name": "tiiuae-falcon-7b-instruct-Q4_K_M"
      },
      "most_capable": {
        "name": "tiiuae-falcon-7b-Q6_K.gguf"
      }
    },
    "all": [
      {
        "name": "tiiuae-falcon-7b-instruct-Q2_K.gguf",
        "url": "https://huggingface.co/maddes8cht/tiiuae-falcon-7b-instruct-gguf/blob/main/tiiuae-falcon-7b-instruct-Q2_K.gguf",
        "sizeBytes": 4025162688,
        "quantization": "Q2_K",
        "format": "gguf",
        "sha256checksum": "c0e87b27def08c0a9dc8fa9bfd70cd7bc373d328943530984165ac4b20d2202c",
        "publisher": {
          "name": "maddes8cht",
          "socialUrl": "https://twitter.com/maddes1966"
        },
        "respository": "maddes8cht/tiiuae-falcon-7b-instruct-gguf",
        "repositoryUrl": "https://huggingface.co/maddes8cht/tiiuae-falcon-7b-instruct-gguf"
      },
      {
        "name": "tiiuae-falcon-7b-instruct-Q4_K_M.gguf",
        "url": "https://huggingface.co/maddes8cht/tiiuae-falcon-7b-instruct-gguf/blob/main/tiiuae-falcon-7b-instruct-Q4_K_M.gguf",
        "sizeBytes": 4975385792,
        "quantization": "Q4_K_M",
        "format": "gguf",
        "sha256checksum": "6f6c886ed07d4f6133a4dd7f8b799764ed719c50973d96816b2ac5ff3ada9913",
        "publisher": {
          "name": "maddes8cht",
          "socialUrl": "https://twitter.com/maddes1966"
        },
        "respository": "maddes8cht/tiiuae-falcon-7b-instruct-gguf",
        "repositoryUrl": "https://huggingface.co/maddes8cht/tiiuae-falcon-7b-instruct-gguf"
      },
      {
        "name": "tiiuae-falcon-7b-instruct-Q5_K_M.gguf",
        "url": "https://huggingface.co/maddes8cht/tiiuae-falcon-7b-instruct-gguf/blob/main/tiiuae-falcon-7b-instruct-Q5_K_M.gguf",
        "sizeBytes": 5731380160,
        "quantization": "Q5_K_M",
        "format": "gguf",
        "sha256checksum": "3a4666a200024584f667b4dcf2761463046924f9b0708ba13315831416d8548a",
        "publisher": {
          "name": "maddes8cht",
          "socialUrl": "https://twitter.com/maddes1966"
        },
        "respository": "maddes8cht/tiiuae-falcon-7b-instruct-gguf",
        "repositoryUrl": "https://huggingface.co/maddes8cht/tiiuae-falcon-7b-instruct-gguf"
      },
      {
        "name": "tiiuae-falcon-7b-instruct-Q6_K.gguf",
        "url": "https://huggingface.co/maddes8cht/tiiuae-falcon-7b-instruct-gguf/blob/main/tiiuae-falcon-7b-instruct-Q6_K.gguf",
        "sizeBytes": 7031618496,
        "quantization": "Q6_K",
        "format": "gguf",
        "sha256checksum": "e6b23eb4193b2d8c7effb4870d2db7a3faa6ed2c8f2c075f7ced51591938818a",
        "publisher": {
          "name": "maddes8cht",
          "socialUrl": "https://twitter.com/maddes1966"
        },
        "respository": "maddes8cht/tiiuae-falcon-7b-instruct-gguf",
        "repositoryUrl": "https://huggingface.co/maddes8cht/tiiuae-falcon-7b-instruct-gguf"
      }
    ]
  }
}

=== lmstudio-ai/model-catalog/models/Llama-3-8B-Instruct.json
{
  "_descriptorVersion": "0.0.1",  
  "datePublished": "2024-04-19T01:00:31.000Z",
  "name": "Llama 3 - 8B Instruct",
  "description": "MetaAI's latest Llama model is here. Llama 3 comes in two sizes: 8B and 70B. Llama 3 is pretrained on over 15T tokens that were all collected from publicly available sources. Meta's training dataset is seven times larger than that used for Llama 2, and it includes four times more code.",
  "author": {
    "name": "Meta AI",
    "url": "https://ai.meta.com",
    "blurb": "Pushing the boundaries of AI through research, infrastructure and product innovation."
  },
  "numParameters": "7B",
  "resources": {
    "canonicalUrl": "https://llama.meta.com/llama3/",
    "paperUrl": "https://ai.meta.com/blog/meta-llama-3/",
    "downloadUrl": "https://huggingface.co/lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF"
  },
  "trainedFor": "chat",
  "arch": "llama",
  "files": {
    "highlighted": {
      "economical": {
        "name": "Meta-Llama-3-8B-Instruct-Q4_K_M.gguf"
      }
    },
    "all": [
      {
        "name": "Meta-Llama-3-8B-Instruct-Q4_K_M.gguf",
        "url": "https://huggingface.co/lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF/resolve/main/Meta-Llama-3-8B-Instruct-Q4_K_M.gguf",
        "sizeBytes": 4920733888,
        "quantization": "Q4_K_S",
        "format": "gguf",
        "sha256checksum": "ab9e4eec7e80892fd78f74d9a15d0299f1e22121cea44efd68a7a02a3fe9a1da",
        "publisher": {
          "name": "lmstudio-community",
          "socialUrl": "https://huggingface.co/lmstudio-community"
        },
        "respository": "lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF",
        "repositoryUrl": "https://huggingface.co/lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF"
      }
    ]
  }
}
